name: Reformat code

on:
  push:
    branches-ignore: ["update-format--**", "release-please--**"]
  workflow_dispatch:

jobs:
  update-format:
    name: Reformat code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Rebuild the dist/ directory
        run: bun run format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "style: reformat code on ${{ github.ref_name }}"
          commit-message: "style: reformat code"
          body: "Reformatted code using biome"
          branch: update-format--${{ github.ref_name }}
          delete-branch: true
          labels: bot,dist
